name: duty_free_lens
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  splashscreen: ^1.3.5
  country_list_pick: ^1.0.1+3
  country_currency_pickers: ^1.0.1
  firebase_ml_vision: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
